apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: workload
spec:
  template:
    spec:
      nodeClassRef:
        name: default
        kind: EC2NodeClass
        group: karpenter.k8s.aws
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.nano", "t3.micro", "t3.small"]
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
